{
 "title": "Servers",
 "time": { "from": "now-24h", "to": "now-5m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Host", "label": "Host", "query": "*-Host-*" }
  ]
 },
 "panels": [
  {
   "title": "Load medterm",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(aliasSub($Host.load.*.midterm, '(-Host-)', '-'), 0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 3,
     "target": "aliasByNode(divideSeries(AMS-Host-1.memory.memory-used, #B), 0)",
     "targetFull": "aliasByNode(divideSeries(AMS-Host-1.memory.memory-used, sumSeries(AMS-Host-1.memory.memory-[fubc]*)), 0)"
    },
    {
     "refCount": 2,
     "target": "aliasByNode(divideSeries(AMS-Host-2.memory.memory-used, #D), 0)",
     "targetFull": "aliasByNode(divideSeries(AMS-Host-2.memory.memory-used, sumSeries(AMS-Host-2.memory.memory-[fubc]*)), 0)"
    },
    {
     "refCount": 2,
     "target": "aliasByNode(divideSeries(FR-Host-1.memory.memory-used, #F), 0)",
     "targetFull": "aliasByNode(divideSeries(FR-Host-1.memory.memory-used, sumSeries(FR-Host-1.memory.memory-[fubc]*)), 0)"
    },
    {
     "refCount": 3,
     "target": "aliasByNode(divideSeries(FR-Host-2.memory.memory-used, #H), 0)",
     "targetFull": "aliasByNode(divideSeries(FR-Host-2.memory.memory-used, sumSeries(FR-Host-2.memory.memory-[fubc]*)), 0)"
    }
   ]
  },
  {
   "title": "DF /",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 3,
     "target": "aliasSub(aliasByNode(divideSeries(AMS-Host-1.df-root.df_complex-free, #B), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(AMS-Host-1.df-root.df_complex-free, sumSeries(AMS-Host-1.df-root.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(aliasByNode(divideSeries(AMS-Host-2.df-root.df_complex-free, #D), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(AMS-Host-2.df-root.df_complex-free, sumSeries(AMS-Host-2.df-root.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(aliasByNode(divideSeries(FR-Host-1.df-root.df_complex-free, #F), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(FR-Host-1.df-root.df_complex-free, sumSeries(FR-Host-1.df-root.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByNode(divideSeries(FR-Host-2.df-root.df_complex-free, #H), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(FR-Host-2.df-root.df_complex-free, sumSeries(FR-Host-2.df-root.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    }
   ]
  },
  {
   "title": "DF /home",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "refCount": 2,
     "target": "aliasSub(aliasByNode(divideSeries(AMS-Host-1.df-home.df_complex-free, #B), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(AMS-Host-1.df-home.df_complex-free, sumSeries(AMS-Host-1.df-home.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(aliasByNode(divideSeries(AMS-Host-2.df-home.df_complex-free, #D), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(AMS-Host-2.df-home.df_complex-free, sumSeries(AMS-Host-2.df-home.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    },
    {
     "refCount": 2,
     "target": "aliasSub(aliasByNode(divideSeries(FR-Host-1.df-home.df_complex-free, #F), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(FR-Host-1.df-home.df_complex-free, sumSeries(FR-Host-1.df-home.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    },
    {
     "refCount": 3,
     "target": "aliasSub(aliasByNode(divideSeries(FR-Host-2.df-home.df_complex-free, #H), 0), '(-Host-)', ' ')",
     "targetFull": "aliasSub(aliasByNode(divideSeries(FR-Host-2.df-home.df_complex-free, sumSeries(FR-Host-2.df-home.df_complex-[fu]*)), 0), '(-Host-)', ' ')"
    }
   ]
  },
  {
   "title": "CPU idle",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode($Host.cpu*.cpu-idle, 0, 'avg'), '(-Host-)', '-')"
    }
   ]
  },
  {
   "title": "CPU wait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode($Host.cpu*.cpu-wait, 0, 'avg'), '(-Host-)', '-')"
    }
   ]
  },
  {
   "title": "CPU softirq",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode($Host.cpu*.cpu-softirq, 0, 'avg'), '(-Host-)', '-')"
    }
   ]
  },
  {
   "title": "CPU interrupt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasSub(groupByNode($Host.cpu*.cpu-interrupt, 0, 'avg'), '(-Host-)', '-')"
    }
   ]
  }
 ]
}